version: '3'

services:
  postgres:
    image: postgres:14.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    build:
      context: .
      dockerfile: Dockerfile.maildev
    ports:
      - '1080:1025'

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    expose:
      - 6379
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - postgres
